/*
 * The protocol card bank. JSON-pure, validated by engine.validateData().
 *
 * Every number here traces to the research digest (Walker, Attia/Outlive,
 * Galpin, Laukkanen, Søberg, Holt-Lunstad, Huberman Lab, Blueprint) and the
 * primary literature behind it. Evidence grades are applied honestly:
 * strong = good human trials / large consistent cohorts; moderate = decent
 * human evidence with caveats; emerging = interesting but unproven.
 *
 * Rules of the bank (enforced by tests):
 * - supplements carry tags:['supplement'] + a pharmacist/doctor caution;
 * - vigorous cardio carries tags:['vigorous_exercise'];
 * - heat/cold/fasting/calorie/weight framing carry their tags for flag suppression;
 * - attribution is to primary researchers/books, never celebrity endorsement;
 * - structure/function language only — no prevent/treat/cure/reverse-aging.
 */

'use strict';

const PROTOCOLS = [
  /* =============================================================== SLEEP */
  {
    id: 'fixed-wake-time', domain: 'sleep', tier: 'free', priority: 98,
    title: 'Fix your wake-up time first',
    tldr: 'A consistent bed and wake time predicts mortality more strongly than how long you sleep. That makes it the first thing to fix.',
    why: 'In a 2024 analysis of over 60,000 people (Windred et al., SLEEP), how regular someone’s sleep timing was predicted death more strongly than how many hours they slept. The wake time is the easier end to anchor, because you can set an alarm; the body then drifts the bedtime earlier on its own.',
    how: [
      'Pick one wake time you can hold seven days a week — yes, including weekends.',
      'Set it, put the alarm across the room, and keep it fixed even after a bad night.',
      'Go to bed when you first feel sleepy rather than pushing through the “second wind”.',
      'Give it two weeks before you judge it; the bedtime end settles gradually.',
    ],
    evidence: 'strong', effort: 2, cost: 'free',
    attribution: [{ who: 'Windred et al.', what: 'Sleep regularity vs duration and mortality, SLEEP (2024)' }, { who: 'Matthew Walker', what: 'Why We Sleep — regularity (the R in QQRT)' }],
    triggers: { domain_below: 90, answers: [{ q: 'sleep_consistency', in: ['hourish', 'chaos'] }] },
  },
  {
    id: 'morning-light', domain: 'sleep', tier: 'free', priority: 95,
    title: 'Get outside light within an hour of waking',
    tldr: 'Morning outdoor light is the strongest free lever for setting your body clock. It makes the night’s sleep easier weeks later.',
    why: 'Bright morning light anchors the circadian clock and brings your natural sleep signal forward in the evening. It has to reach your eyes directly: outdoor light is thousands of times brighter than indoor light even on a grey day, and a window blocks most of the effect.',
    how: [
      'Get outside within 30–60 minutes of waking. No sunglasses; ordinary glasses or contacts are fine.',
      'Roughly 10 minutes on a bright day, 20 on a cloudy one, 30+ if it’s heavily overcast.',
      'Pair it with something you already do — coffee on the step, the first dog walk, part of the commute.',
      'Never look directly at the sun; “bright sky” is the target, not the disc.',
    ],
    evidence: 'moderate', effort: 1, cost: 'free',
    attribution: [{ who: 'Huberman Lab', what: 'Sleep toolkit — morning light timing and duration' }],
    triggers: { answers: [{ q: 'morning_light', in: ['sometimes', 'rarely'] }, { q: 'sleep_consistency', in: ['hourish', 'chaos'] }] },
  },
  {
    id: 'cool-dark-room', domain: 'sleep', tier: 'free', priority: 88,
    title: 'Make the room cool and properly dark',
    tldr: 'Your core temperature has to drop a degree or two to fall and stay asleep. A room around 18°C helps it happen.',
    why: 'Falling asleep depends on core body temperature dropping by 1–3°F. A cool room (roughly 18°C / 65°F) makes that easier; a warm one fights it. Darkness matters because even modest light late at night nudges the clock the wrong way.',
    how: [
      'Aim for around 18°C / 65°F — cooler than feels obviously comfortable when you get in.',
      'A warm shower an hour before bed helps: the rebound cooling afterwards drops your core temperature.',
      'If you run hot, stick a foot out from under the covers — it dumps heat surprisingly well.',
      'Block light: curtains, an eye mask, and turn phone and standby LEDs away from the bed.',
    ],
    evidence: 'moderate', effort: 1, cost: 'free',
    attribution: [{ who: 'Matthew Walker', what: 'Why We Sleep — bedroom temperature ~18°C' }, { who: 'Huberman Lab', what: 'Temperature and sleep onset' }],
    triggers: { domain_below: 85 },
  },
  {
    id: 'phone-out-of-bedroom', domain: 'sleep', tier: 'free', priority: 80,
    title: 'Charge your phone in another room',
    tldr: 'The problem isn’t mainly blue light. It’s that the phone keeps your brain switched on when it should be powering down.',
    why: 'Bright overhead light and screens late at night blunt melatonin, but the bigger effect for most people is behavioural: one more scroll, one more video, and the wind-down never starts. Removing the phone from arm’s reach removes the decision.',
    how: [
      'Charge the phone in another room, or at least across this one — out of reach from the bed.',
      'Buy a cheap alarm clock so “I need it for the alarm” stops being the excuse.',
      'Dim the lights in the last hour; use low, warm lamps rather than the ceiling light.',
      'If you read, read something on paper.',
    ],
    evidence: 'moderate', effort: 2, cost: 'low',
    attribution: [{ who: 'Huberman Lab', what: 'Evening light and sleep' }, { who: 'Matthew Walker', what: 'Why We Sleep — screens before bed' }],
    triggers: { answers: [{ q: 'phone_bed', in: ['in_bed', 'nearby'] }] },
  },
  {
    id: 'caffeine-cutoff', domain: 'sleep', tier: 'free', priority: 78,
    title: 'Draw a caffeine line in the early afternoon',
    tldr: 'Caffeine has a long half-life; an afternoon coffee is still in your system at bedtime even if you fall asleep fine.',
    why: 'Caffeine’s half-life is roughly 5–6 hours, so a quarter of a 2pm coffee is still circulating at 10pm. It can shave deep sleep even when it doesn’t stop you dropping off. Cutting it 8–10 hours before bed removes the hidden tax.',
    how: [
      'Work back 8–10 hours from your bedtime — that’s your cut-off (often early afternoon).',
      'Matthew Walker argues for an even earlier line, around noon, if your sleep is fragile.',
      'Watch the sneaky sources: green tea, pre-workout, dark chocolate, some painkillers.',
      'Delaying your first coffee to 90–120 minutes after waking also steadies afternoon energy.',
    ],
    evidence: 'moderate', effort: 1, cost: 'free',
    attribution: [{ who: 'Huberman Lab', what: 'Caffeine timing (8–10h before bed)' }, { who: 'Matthew Walker', what: 'Why We Sleep — caffeine half-life' }],
    triggers: { answers: [{ q: 'caffeine_late', in: ['sometimes', 'daily'] }, { q: 'wake_refreshed', in: ['mixed', 'rough'] }] },
  },
  {
    id: 'wind-down-routine', domain: 'sleep', tier: 'pro', priority: 70,
    title: 'Build a 30–60 minute wind-down',
    tldr: 'Sleep is a landing, not a light switch. A short, repeatable routine tells your body the runway is clear.',
    why: 'The nervous system needs a descent, not an off-button. A consistent wind-down — same steps, same order — becomes a signal your body learns to read, so sleep arrives faster and holds better. This is the behavioural backbone under every sleep supplement people reach for first.',
    how: [
      'Give yourself 30–60 minutes of the same low-key steps each night, in the same order.',
      'Dim lights, finish eating 2–3 hours before bed, and keep the last hour screen-light.',
      'If your mind races, keep a “worry pad” by the bed and write tomorrow’s list out of your head.',
      'If you’re awake more than ~20 minutes, get up, do something dull in dim light, and return when sleepy.',
    ],
    evidence: 'moderate', effort: 2, cost: 'free',
    attribution: [{ who: 'Matthew Walker', what: 'Why We Sleep — wind-down and the 20-minute rule' }],
    triggers: { domain_below: 70 },
  },
  {
    id: 'nsdr-for-sleep-debt', domain: 'sleep', tier: 'pro', priority: 55,
    title: 'Use NSDR to claw back a rough night',
    tldr: 'A 10–20 minute non-sleep-deep-rest session won’t replace sleep, but it measurably restores energy and focus after a bad night.',
    why: 'NSDR (Non-Sleep Deep Rest), essentially guided yoga nidra, is a lie-still practice that lowers arousal and restores alertness and dopamine. It’s not a substitute for sleep, but it’s a genuinely useful patch on the days sleep was short — and free.',
    how: [
      'Find a free 10- or 20-minute NSDR or yoga-nidra track (several are on YouTube at no cost).',
      'Lie down somewhere you won’t be disturbed; follow the voice, don’t try to sleep.',
      'Use it early afternoon after a short night, or to get back to sleep at 3am.',
      'If you nap instead, keep it under ~90 minutes so it doesn’t wreck the coming night.',
    ],
    evidence: 'emerging', effort: 1, cost: 'free',
    attribution: [{ who: 'Huberman Lab', what: 'NSDR / yoga nidra protocols' }],
    triggers: { domain_below: 75 },
  },

  /* ============================================================ MOVEMENT */
  {
    id: 'strength-twice-weekly', domain: 'movement', tier: 'free', priority: 96,
    title: 'Lift something heavy twice a week',
    tldr: 'Any resistance training is linked to ~15% lower all-cause mortality; the benefit peaks around an hour a week, then flattens.',
    why: 'A 2022 meta-analysis found any resistance training associated with about 15% lower all-cause mortality, 19% lower cardiovascular and 14% lower cancer mortality, with the benefit peaking near 60 minutes a week. Muscle behaves like a metabolic organ — it helps regulate blood sugar — and strength is one of the clearest predictors of an independent old age.',
    how: [
      'Two sessions a week, 20–40 minutes each, covering the whole body.',
      'Build around compound movements: a squat, a hinge, a push, a pull, a carry.',
      'Start where you are — bodyweight squats, press-ups on the knees, a loaded backpack all count.',
      'Add a little each week: one more rep, slightly more weight. That progression is the whole game.',
    ],
    evidence: 'strong', effort: 2, cost: 'free',
    attribution: [{ who: 'Momma et al.', what: 'Resistance training and mortality meta-analysis, AJPM (2022)' }, { who: 'Peter Attia', what: 'Outlive — strength for the marginal decade' }],
    triggers: { answers: [{ q: 'strength_days', in: ['0', '1'] }] },
  },
  {
    id: 'zone2-base', domain: 'movement', tier: 'free', priority: 90,
    title: 'Build a Zone 2 cardio base',
    tldr: 'Cardiorespiratory fitness is the single strongest modifiable predictor of mortality in the data. The base is built at an easy, conversational pace.',
    why: 'In a study of 122,000 people (Mandsager et al., JAMA 2018), the least-fit group had roughly five times the mortality risk of the fittest — a bigger gap than smoking or diabetes, with no ceiling on the benefit. Most of that fitness is built slowly, at “Zone 2”: an effort you could hold a conversation through.',
    how: [
      'Aim for 150+ minutes a week of easy cardio you can still talk through — brisk walk, cycle, row, swim.',
      'The test is simple: if you can’t speak in full sentences, slow down. Most people go too hard here.',
      'Stack it into your week however fits — three 50-minute blocks, or a daily half-hour.',
      'A brisk walk after meals doubles as blood-sugar management; it counts.',
    ],
    evidence: 'strong', effort: 2, cost: 'free',
    attribution: [{ who: 'Mandsager et al.', what: 'Fitness and mortality, JAMA Network Open (2018)' }, { who: 'Peter Attia', what: 'Outlive — Zone 2 (RPE 6–7, conversational)' }],
    triggers: { answers: [{ q: 'cardio_days', in: ['0', '1', '2'] }] },
  },
  {
    id: 'walk-after-meals', domain: 'movement', tier: 'free', priority: 82,
    title: 'Take a 10-minute walk after meals',
    tldr: 'A short walk after eating blunts the blood-sugar spike and quietly adds to your weekly movement without feeling like exercise.',
    why: 'Light walking after a meal helps muscles pull glucose out of the blood, flattening the post-meal spike. It’s the lowest-friction movement there is — no kit, no changing, no gym — and it chips away at the hours you’d otherwise spend sitting.',
    how: [
      'Ten minutes after your biggest meal is the highest-value slot; after every meal is better still.',
      'Keep it gentle — this is a stroll, not a march.',
      'Anchor it to the meal so it becomes automatic: eat, shoes, door.',
      'On a wet day, laps of the house or stairs count.',
    ],
    evidence: 'moderate', effort: 1, cost: 'free',
    attribution: [{ who: 'Buffey et al.', what: 'Light walking after meals and glycaemia, Sports Medicine (2022)' }],
    triggers: { answers: [{ q: 'sitting_hours', in: [] }], domain_below: 80 },
  },
  {
    id: 'break-up-sitting', domain: 'movement', tier: 'free', priority: 76,
    title: 'Stand up every half hour',
    tldr: 'Long unbroken sitting carries its own risk. Breaking it up regularly matters even if you exercise otherwise.',
    why: 'Prolonged uninterrupted sitting is associated with worse metabolic and mortality outcomes somewhat independently of how much you exercise. The fix isn’t a standing desk you hate; it’s frequent short interruptions to the sitting itself.',
    how: [
      'Every 30 minutes, stand and move for 2–3 minutes — kettle, stairs, a lap of the office.',
      'Tie breaks to triggers you already have: end of a meeting, an advert break, a sent email.',
      'Take calls on your feet or walking.',
      'If you can, alternate sitting and standing through the day rather than committing to either.',
    ],
    evidence: 'moderate', effort: 1, cost: 'free',
    attribution: [{ who: 'Diaz et al.', what: 'Sedentary bout length and mortality, Annals of Internal Medicine (2017)' }],
    triggers: { answers: [{ q: 'sitting_hours', in: [] }] },
  },
  {
    id: 'vo2max-intervals', domain: 'movement', tier: 'pro', priority: 74,
    title: 'Add one hard interval session a week',
    tldr: 'One weekly session of hard intervals is the fastest way to raise VO₂max. The fitness measure most tightly tied to living longer.',
    why: 'On top of an easy Zone 2 base, a single weekly session of hard intervals drives VO₂max up quickly. The classic “Norwegian 4×4” — four 4-minute efforts near your max with easy recovery between — produced roughly 7–10% VO₂max gains over eight weeks in the original NTNU work.',
    how: [
      'Warm up well. Then 4 rounds of: 4 minutes hard (you couldn’t hold a conversation), 3 minutes easy.',
      'Use anything sustained and safe: a hill, a bike, a rower, a ski erg, stairs.',
      '“Hard” should feel like a 8–9 out of 10, not an all-out sprint you can’t finish.',
      'Once a week is plenty; this is the session you don’t stack on top of a bad-sleep day.',
    ],
    evidence: 'strong', effort: 3, cost: 'free',
    tags: ['vigorous_exercise'],
    cautions: ['Hard intervals raise heart rate sharply. If you’re over 40 and new to intense exercise, or have any cardiac history, get the all-clear from a doctor before starting.'],
    attribution: [{ who: 'Helgerud & Hoff (NTNU)', what: 'Norwegian 4×4 interval protocol' }, { who: 'Peter Attia', what: 'Outlive — VO₂max training' }],
    triggers: { domain_below: 70, exclude_flags: ['heart_symptoms'] },
  },
  {
    id: 'strength-benchmarks', domain: 'movement', tier: 'pro', priority: 60,
    title: 'Test yourself: dead hang, carry, grip',
    tldr: 'Grip strength alone tracks mortality. Each 5kg drop is linked to ~16% higher risk. These self-tests need no lab and give you a number to beat.',
    why: 'In the PURE study (~140,000 people), every 5kg fall in grip strength was associated with about 16% higher all-cause mortality — a stronger signal than systolic blood pressure. A handful of simple physical tests give you honest baselines and something concrete to train toward.',
    how: [
      'Dead hang from a bar: a rough functional target is ~2 minutes for men, ~90 seconds for women.',
      'Farmer carry: work toward carrying about your bodyweight (split between two hands) for a minute.',
      'Retest every 8–12 weeks and watch the number, not the mirror.',
      'Train the lifts these reflect — deadlifts, carries, rows, hangs — and the benchmarks follow.',
    ],
    evidence: 'strong', effort: 2, cost: 'free',
    attribution: [{ who: 'Leong et al. (PURE study)', what: 'Grip strength and mortality, The Lancet (2015)' }, { who: 'Peter Attia', what: 'Outlive — strength benchmarks' }],
    triggers: { domain_below: 80, exclude_flags: ['heart_symptoms'] },
  },

  /* =========================================================== NUTRITION */
  {
    id: 'crowd-out-ultraprocessed', domain: 'nutrition', tier: 'free', priority: 92,
    title: 'Shift the balance toward real food',
    tldr: 'Each 10% more of your calories from ultra-processed food tracks with higher mortality. The win is crowding it out, not banning it.',
    why: 'A 2024 meta-analysis (~1.15 million people) found the highest ultra-processed-food eaters had about 15% higher all-cause mortality than the lowest, roughly dose-dependent. You don’t need a perfect diet — you need real food to take up more of the plate than the packet does.',
    how: [
      'Anchor meals on things without a long ingredient list: vegetables, fruit, beans, eggs, fish, meat, plain dairy, whole grains.',
      'Change defaults rather than willpower: what’s in the fridge at eye level, what’s on the counter.',
      'Cook one more meal a week from scratch than you do now. Repeat next month.',
      'Don’t aim for zero processed food — aim for it being the minority, reliably.',
    ],
    evidence: 'strong', effort: 2, cost: 'free',
    attribution: [{ who: 'Lane et al.', what: 'Ultra-processed food and health outcomes umbrella review, BMJ (2024)' }, { who: 'Peter Attia', what: 'Outlive — dietary pattern over dogma' }],
    triggers: { answers: [{ q: 'diet_pattern', in: ['mixed', 'processed'] }] },
  },
  {
    id: 'protein-at-every-meal', domain: 'nutrition', tier: 'free', priority: 86,
    title: 'Put protein at every meal',
    tldr: 'Protein defends muscle as you age. Most people, especially older adults, eat less than is ideal for that.',
    why: 'Adequate protein, spread across the day, is what lets resistance training build and hold muscle — the tissue that protects your metabolism and independence. Attia argues the standard 0.8 g/kg guideline is too low for active and older people, pointing toward roughly 1.6 g/kg, though the literature for older adults sits nearer 1.0–1.6.',
    how: [
      'Get a palm-sized source of protein into each meal: eggs, fish, meat, tofu, dairy, beans, lentils.',
      'Breakfast is where most people miss it — a protein-forward first meal is the easiest fix.',
      'A rough, non-fussy target: a source at every meal plus one protein-heavy snack.',
      'Plant or animal both work; variety across the week covers the bases.',
    ],
    evidence: 'moderate', effort: 1, cost: 'free',
    attribution: [{ who: 'Peter Attia', what: 'Outlive — protein 1.6–2.2 g/kg for active/older adults' }],
    triggers: { answers: [{ q: 'protein_meals', in: ['some', 'rarely'] }] },
  },
  {
    id: 'fibre-and-plants', domain: 'nutrition', tier: 'free', priority: 80,
    title: 'Aim for 30 different plants a week',
    tldr: 'Fibre intake around 25–29 g/day tracks with 15–30% lower mortality. Counting plant variety is an easier target than grams.',
    why: 'A 2019 Lancet meta-analysis found the highest fibre eaters had 15–30% lower all-cause and cardiovascular mortality, with benefit around 25–29 g a day. Chasing plant variety rather than a gram count also feeds a wider gut microbiome, and it’s a target you can actually picture.',
    how: [
      'Count plant types across a week — vegetables, fruit, beans, nuts, seeds, whole grains, herbs all count.',
      'Thirty distinct plants a week is the well-known target; even climbing from 10 to 20 is real progress.',
      'Cheapest high-fibre wins: tinned beans and lentils, frozen veg, oats, a piece of fruit as default snack.',
      'Add fibre gradually and drink water, or your gut will file a complaint.',
    ],
    evidence: 'strong', effort: 2, cost: 'low',
    attribution: [{ who: 'Reynolds et al.', what: 'Carbohydrate quality and health, The Lancet (2019)' }, { who: 'McDonald et al. (American Gut)', what: '≥30 plants/week and microbiome diversity (2018)' }],
    triggers: { answers: [{ q: 'veg_servings', in: [] }], domain_below: 80 },
  },
  {
    id: 'overnight-eating-gap', domain: 'nutrition', tier: 'free', priority: 62,
    title: 'Leave a gap between dinner and bed',
    tldr: 'Finishing food a few hours before sleep helps digestion and sleep quality. Without any need for aggressive fasting.',
    why: 'Eating late competes with sleep: digestion keeps your core temperature and metabolism up when they should be settling. A simple overnight gap — not an extreme fasting protocol — captures most of the benefit people chase with complicated eating windows.',
    how: [
      'Finish eating 2–3 hours before bed on most nights.',
      'If you’re hungry later, something small and light beats a full meal.',
      'This is a gentle default, not a rule to enforce when life gets in the way.',
    ],
    evidence: 'emerging', effort: 1, cost: 'free',
    tags: ['fasting'],
    cautions: ['This is about meal timing, not skipping meals or cutting calories. If you have any history of disordered eating, ignore this one — a regular eating pattern matters more.'],
    attribution: [{ who: 'Huberman Lab', what: 'Meal timing and sleep' }, { who: 'Bryan Johnson (Blueprint)', what: 'Early final meal (reported)' }],
    triggers: { answers: [{ q: 'last_meal', in: ['late', 'varies'] }] },
  },
  {
    id: 'creatine-monohydrate', domain: 'nutrition', tier: 'free', priority: 70,
    title: 'Consider creatine monohydrate',
    tldr: 'The most-studied, cheapest sports supplement there is. Solid for strength, with early signals for cognition in older and sleep-deprived people.',
    why: 'Creatine monohydrate has decades of human trials behind it for strength and lean mass when paired with training, and a 2024 review (16 RCTs) points to emerging cognitive benefit, strongest in older adults and under stress. It’s one of the few supplements where the evidence is genuinely strong and the cost is trivial.',
    how: [
      'The standard dose is 3–5 g a day of plain creatine monohydrate — no need for fancy blends.',
      'Timing doesn’t matter; take it whenever you’ll remember. Consistency is what counts.',
      'You don’t need a “loading phase”; it just takes a few weeks to saturate at 3–5 g/day.',
      'Buy a third-party-tested product (NSF or Informed Sport). Plain monohydrate is the cheapest form and the one that was studied.',
    ],
    evidence: 'strong', effort: 1, cost: 'low',
    tags: ['supplement'],
    cautions: ['Supplements aren’t regulated like medicines. Check with a pharmacist or doctor before starting anything, especially if you have kidney issues or take regular medication. We sell nothing and earn nothing from this suggestion.'],
    attribution: [{ who: 'Kreider et al.', what: 'Creatine safety and efficacy review, JISSN' }, { who: 'Prokopidis et al.', what: 'Creatine and cognition meta-analysis (2023)' }],
    triggers: { exclude_flags: ['pregnant', 'meds'] },
  },
  {
    id: 'omega3-basics', domain: 'nutrition', tier: 'pro', priority: 55,
    title: 'Omega-3s: food first, then maybe a supplement',
    tldr: 'Oily fish a couple of times a week is the well-evidenced move; a fish-oil supplement is a reasonable backup, with real caveats.',
    why: 'Higher omega-3 intake is associated with better cardiovascular markers, and 2–4 g/day of EPA+DHA lowers triglycerides meaningfully. But high-dose supplements have given mixed trial results — one large trial even signalled harm in people with existing heart disease — so this sits below the food-first version, not above it.',
    how: [
      'First choice: oily fish (salmon, mackerel, sardines) two or three times a week.',
      'If you don’t eat fish, a supplement providing around 1–2 g/day combined EPA+DHA is reasonable.',
      'Choose a third-party-tested product; store it cool so it doesn’t go rancid.',
      'If you have heart disease or take blood thinners, this is a conversation for your doctor, not a self-start.',
    ],
    evidence: 'moderate', effort: 1, cost: 'low',
    tags: ['supplement'],
    cautions: ['High-dose fish oil can affect bleeding and gave mixed results in trials for people with existing cardiovascular disease. Talk to a doctor before supplementing if that’s you. We have no financial interest in any product.'],
    attribution: [{ who: 'Rhonda Patrick', what: 'Omega-3 index target ~8% (FoundMyFitness)' }, { who: 'REDUCE-IT / STRENGTH trials', what: 'Mixed high-dose EPA outcomes' }],
    triggers: { exclude_flags: ['pregnant', 'meds'] },
  },
  {
    id: 'vitamin-d-insufficiency', domain: 'nutrition', tier: 'pro', priority: 40,
    title: 'Vitamin D: correct a deficiency, don’t chase a longevity effect',
    tldr: 'The big trial found no mortality or cancer benefit from supplementing generally. It’s worth it to fix a genuine deficiency, not as a longevity lever.',
    why: 'The VITAL trial (25,871 people, 2000 IU/day) found no reduction in total cancer or all-cause mortality. So the honest framing is narrow: vitamin D is worth taking if you’re actually deficient — common at higher latitudes in winter or with little sun exposure — not as a general anti-ageing pill.',
    how: [
      'If you get little sunlight (northern winter, mostly indoors, darker skin), a modest daily dose (often ~1000–2000 IU) is reasonable.',
      'The only way to know if you need it is a blood test — ask your GP rather than guessing.',
      'More is not better; very high doses carry their own risks.',
    ],
    evidence: 'moderate', effort: 1, cost: 'low',
    tags: ['supplement'],
    cautions: ['Get your level checked before supplementing at higher doses. A pharmacist or GP can advise. We sell nothing here.'],
    attribution: [{ who: 'Manson et al. (VITAL trial)', what: 'Vitamin D and mortality/cancer, NEJM (2019)' }],
    triggers: { exclude_flags: ['pregnant', 'meds'] },
  },

  /* ================================================================ MIND */
  {
    id: 'physiological-sigh', domain: 'mind', tier: 'free', priority: 88,
    title: 'Learn the physiological sigh',
    tldr: 'A specific double-inhale, long-exhale breath calms you down in real time. Five minutes a day of slow breathing beat other practices for mood in a controlled trial.',
    why: 'A 2023 Stanford study (Balban et al., Cell Reports Medicine) compared breathwork and mindfulness over a month; five minutes a day of slow, exhale-emphasised breathing improved mood and lowered resting breathing rate more than the meditation arm. The “physiological sigh” — two inhales then a long exhale — is the fastest single-breath version for an acute stress spike.',
    how: [
      'In the moment: inhale through the nose, sneak a second small inhale on top, then a long slow exhale. Repeat 1–3 times.',
      'As a daily practice: five minutes of slow breathing with the exhale longer than the inhale.',
      'Use the sigh before a hard conversation, in traffic, mid-inbox — anywhere the stress is real and brief.',
      'It works because the long exhale shifts you toward the “rest” side of the nervous system. No app required.',
    ],
    evidence: 'moderate', effort: 1, cost: 'free',
    attribution: [{ who: 'Balban et al.', what: 'Breathwork vs mindfulness for mood, Cell Reports Medicine (2023)' }],
    triggers: { answers: [{ q: 'stress', in: ['weeks', 'most'] }, { q: 'downshift', in: ['kinda', 'no'] }] },
  },
  {
    id: 'daily-walk-for-mood', domain: 'mind', tier: 'free', priority: 82,
    title: 'Walk outside every day, for your head',
    tldr: 'A daily outdoor walk is one of the most reliable low-cost levers for mood and stress. Doubling as light exposure and movement.',
    why: 'Regular physical activity has antidepressant-scale effects on mood in trials, and doing it outdoors stacks daylight and often a change of scene on top. It’s not a cure for clinical depression, but for the ordinary weight of a stressful stretch it’s about as good a free tool as exists.',
    how: [
      'A daily walk of 20–30 minutes, ideally outside and ideally not on the phone.',
      'Morning walks pull double duty as circadian light for your sleep.',
      'Let it be dull and repetitive — the reliability is the point, not the scenery.',
      'If mood is low, lower the bar to “shoes on, end of the street” and let momentum do the rest.',
    ],
    evidence: 'strong', effort: 1, cost: 'free',
    attribution: [{ who: 'Recchia et al.', what: 'Physical activity and depression dose-response, BJSM (2022)' }],
    triggers: { answers: [{ q: 'mood', in: ['updown', 'low'] }, { q: 'stress', in: ['weeks', 'most'] }] },
  },
  {
    id: 'talk-to-someone', domain: 'mind', tier: 'free', priority: 90,
    title: 'Talking to a professional is a strong move, not a last resort',
    tldr: 'Therapy has evidence on par with medication for many people. Asking for it is one of the most effective things on this whole site.',
    why: 'For persistent low mood or anxiety, structured talking therapies have trial evidence comparable to antidepressants for many people, without the side effects. The habits on this page help at the margins; they are not a substitute for actual support when things are genuinely heavy.',
    how: [
      'Start with your GP — they can point you to talking therapy and rule out physical causes.',
      'In the UK you can self-refer to NHS Talking Therapies without seeing a GP first.',
      'If cost is the barrier, ask about low-cost or sliding-scale services and community options.',
      'If things feel unsafe right now: 988 (US), 116 123 (Samaritans, UK & Ireland), or findahelpline.com anywhere.',
    ],
    evidence: 'strong', effort: 2, cost: 'medium',
    attribution: [{ who: 'Cuijpers et al.', what: 'Psychotherapy vs pharmacotherapy meta-analyses, World Psychiatry' }],
    triggers: { answers: [{ q: 'mood', in: ['low', 'heavy'] }], domain_below: 45 },
  },
  {
    id: 'meditation-honestly', domain: 'mind', tier: 'pro', priority: 60,
    title: 'Try meditation — with realistic expectations',
    tldr: 'The evidence is real but modest: roughly antidepressant-scale effects on anxiety at eight weeks, and you don’t need a paid app.',
    why: 'Goyal’s JAMA Internal Medicine meta-analysis (47 trials, active controls) found meditation programmes produced moderate improvements in anxiety (effect size ~0.38) and depression (~0.30) at eight weeks — genuine, but not miraculous. Worth trying, worth not overselling to yourself.',
    how: [
      'Start with 10 minutes a day; consistency matters far more than length.',
      'Free options are plenty — guided tracks on YouTube, free tiers, or just following your breath.',
      'Expect a modest lift over weeks, not a transformation. That’s what the trials show.',
      'If sitting still makes anxiety worse, a walking or breath-based practice is a fair substitute.',
    ],
    evidence: 'moderate', effort: 1, cost: 'free',
    attribution: [{ who: 'Goyal et al.', what: 'Meditation programs meta-analysis, JAMA Internal Medicine (2014)' }],
    triggers: { domain_below: 65 },
  },
  {
    id: 'worry-to-paper', domain: 'mind', tier: 'pro', priority: 50,
    title: 'Get tomorrow out of your head and onto paper',
    tldr: 'A short nightly “brain dump” of tomorrow’s worries is a small, evidence-backed way to fall asleep faster and carry less.',
    why: 'A well-known study found people who spent five minutes writing a specific to-do list before bed fell asleep faster than those who journalled about completed tasks. Externalising open loops gives the mind permission to stop rehearsing them.',
    how: [
      'Keep a cheap notebook by the bed.',
      'Before sleep, write tomorrow’s worries and tasks as a specific list — the more concrete, the better.',
      'Close the notebook. The deal is: it’s captured, so you don’t have to keep holding it.',
      'Use the same pad for 3am thoughts instead of reaching for the phone.',
    ],
    evidence: 'emerging', effort: 1, cost: 'free',
    attribution: [{ who: 'Scullin et al.', what: 'Bedtime to-do lists and sleep onset, J. Experimental Psychology (2018)' }],
    triggers: { domain_below: 70 },
  },

  /* ========================================================== CONNECTION */
  {
    id: 'close-relationships-are-core', domain: 'connection', tier: 'free', priority: 95,
    title: 'Keep three people on your 2am list',
    tldr: 'People with strong social ties had 50% higher odds of survival in the largest meta-analysis. An effect the authors put on par with quitting smoking.',
    why: 'Holt-Lunstad’s 2010 meta-analysis pooled 148 studies and 308,849 people: those with stronger social ties had roughly 50% higher odds of being alive at follow-up, an effect the authors put on par with quitting smoking and larger than physical inactivity. It’s observational — illness isolates people too — but it’s one of the most consistent signals in the whole field, which is why connection sits alongside sleep and movement here.',
    how: [
      'List the people you could genuinely call at 2am with a real problem. Fewer than three is a number to grow, not a verdict on you.',
      'Pick one relationship that’s gone quiet and send a message this week — no occasion needed.',
      'Weight your effort toward people nearby; the ties you keep are usually the easy-to-see ones.',
      'Protect the relationships you already have before trying to build new ones — maintenance is cheaper than replacement.',
    ],
    evidence: 'strong', effort: 1, cost: 'free',
    attribution: [{ who: 'Holt-Lunstad, Smith & Layton', what: 'Social relationships and mortality risk meta-analysis, PLOS Medicine (2010)' }],
    triggers: { domain_below: 80 },
  },
  {
    id: 'standing-weekly-social-commitment', domain: 'connection', tier: 'free', priority: 78,
    title: 'Put one social commitment in the diary',
    tldr: 'A standing weekly commitment turns “we should catch up” into contact that actually happens. Frequency, not intention, is what the data track.',
    why: 'Whether you have people matters less than whether you actually see them. In Holt-Lunstad’s work the biggest effects came from how woven into regular activities people were, not from relationships on paper. A standing commitment removes the weakest link — having to organise it from scratch each time.',
    how: [
      'Pick one thing that can repeat: a Sunday walk, a Tuesday call, a monthly dinner.',
      'Put it in the calendar as a recurring event so nobody re-arranges it each week.',
      'Favour face-to-face where you can — that’s where the biggest effects sat.',
      'Keep the bar low. A 30-minute coffee that happens beats a grand plan that doesn’t.',
    ],
    evidence: 'moderate', effort: 2, cost: 'free',
    attribution: [{ who: 'Holt-Lunstad et al.', what: 'Social isolation and mortality, Perspectives on Psychological Science (2015)' }],
    triggers: { domain_below: 72, answers: [{ q: 'two_am', in: ['one_two', 'none'] }] },
  },
  {
    id: 'call-one-person-weekly', domain: 'connection', tier: 'free', priority: 70,
    title: 'Call one person a week, unprompted',
    tldr: 'One short weekly call keeps relationships warm before you need them. Loneliness was linked to 26% higher mortality in pooled data.',
    why: 'A single call won’t move a mortality curve by itself, but it’s the smallest unit of the thing that matters. The 2am list is built in the quiet years, not the crisis. Loneliness was associated with 26% higher mortality in Holt-Lunstad’s 2015 meta-analysis, and regular low-stakes contact is how you keep it from creeping in.',
    how: [
      'Once a week, call — not text — one person you haven’t spoken to in a while.',
      'Keep it short: 10 minutes is plenty. The point is contact, not a summit.',
      'Rotate through a list of 5–10 people so you’re not leaning on one person for everything.',
      'If a call feels heavy, a voice note is a fair substitute — asynchronous still counts.',
    ],
    evidence: 'moderate', effort: 1, cost: 'free',
    attribution: [{ who: 'Holt-Lunstad et al.', what: 'Loneliness and mortality, Perspectives on Psychological Science (2015)' }],
    triggers: { domain_below: 78, answers: [{ q: 'two_am', in: ['none', 'one_two'] }] },
  },
  {
    id: 'volunteer-for-purpose', domain: 'connection', tier: 'pro', priority: 58,
    title: 'Volunteer a couple of hours a week',
    tldr: 'Volunteering is associated with ~24% lower mortality in older adults after adjusting for health. Purpose you can put in a diary.',
    why: 'Okun’s meta-analysis of adults 55+ found volunteering associated with 24% lower mortality after adjusting for health (the unadjusted 47% mostly reflects healthier people volunteering more, so 24% is the honest figure). Purpose overlaps with social contact, which is likely doing some of the work. Observational, so treat it as a strong association rather than proven extra years.',
    how: [
      'Pick something with a fixed slot — a weekly shift or monthly stint — so it becomes a commitment.',
      'Around 100 hours a year (roughly two a week) is where the measured benefit plateaus.',
      'Choose something with other people in it; the benefit sits where purpose and contact overlap.',
      'No formal role handy? A standing commitment to a neighbour or family member counts too.',
    ],
    evidence: 'moderate', effort: 3, cost: 'free',
    attribution: [{ who: 'Okun, Yeung & Brown', what: 'Volunteering and mortality meta-analysis, Psychology & Aging (2013)' }],
    triggers: { domain_below: 70, answers: [{ q: 'purpose', in: ['no', 'sometimes'] }] },
  },
  {
    id: 'regular-contemplative-practice', domain: 'connection', tier: 'pro', priority: 52,
    title: 'Build a regular contemplative practice',
    tldr: 'Prayer, meditation, or a weekly awe walk: moderate trial evidence for lower anxiety, plus observational links to longer life. No belief required.',
    why: 'Two honest strands. On stress: Goyal’s meta-analysis found meditation gave moderate improvements in anxiety at eight weeks. On longevity: Li and VanderWeele’s analysis of 74,534 women found those attending a religious service more than weekly had 33% lower mortality over 16 years — but that figure can’t separate the practice from the community and support around it, so we won’t claim it as cause.',
    how: [
      'Pick one practice that fits you: prayer, silent sitting, a weekly walk somewhere that gives you a sense of awe.',
      'Regularity matters more than intensity — a small weekly ritual beats an occasional grand one.',
      'If community comes with it (a congregation, a group), that’s likely part of the benefit; lean in.',
      'No spiritual belief needed — the stress evidence holds for secular practice too.',
    ],
    evidence: 'emerging', effort: 2, cost: 'free',
    attribution: [{ who: 'Li, VanderWeele et al.', what: 'Religious service attendance and mortality, JAMA Internal Medicine (2016)' }, { who: 'Goyal et al.', what: 'Meditation and anxiety, JAMA Internal Medicine (2014)' }],
    triggers: { domain_below: 75 },
  },

  /* ========================================================== SUBSTANCES */
  {
    id: 'quit-smoking', domain: 'substances', tier: 'free', priority: 100,
    title: 'If you smoke or vape, this is the biggest lever there is',
    tldr: 'Smokers lose about 10 years of life. Quitting before 40 removes roughly 90% of that excess risk, and nothing else on this site comes close.',
    why: 'The evidence here is unusually clear (Jha et al., NEJM 2013): smoking costs around a decade of life, and quitting before age 40 avoids about 90% of the excess death risk. It’s the single highest-value change available to anyone who smokes — which is why it’s the top priority in this whole engine.',
    how: [
      'Quitting cold rarely sticks alone; combine support with nicotine replacement or medication.',
      'In the UK, local Stop Smoking Services roughly triple your odds — free, and they don’t lecture.',
      'In the US, call 1-800-QUIT-NOW or use a cessation programme through your provider.',
      'Vaping is a step down from smoking, but the goal is off nicotine entirely; the same services help.',
      'Lapses are part of quitting, not proof you can’t. Most people who quit did it on a later attempt.',
    ],
    evidence: 'strong', effort: 3, cost: 'free',
    attribution: [{ who: 'Jha et al.', what: '21st-century hazards of smoking and benefits of cessation, NEJM (2013)' }],
    triggers: { answers: [{ q: 'smoking', in: ['daily', 'social'] }] },
  },
  {
    id: 'alcohol-honest', domain: 'substances', tier: 'free', priority: 84,
    title: 'Treat alcohol as something to reduce, not optimise',
    tldr: 'The old “glass of red is good for you” story doesn’t survive the better studies. There’s no intake with a clear survival benefit.',
    why: 'A meta-analysis of 107 cohorts (>4.8 million people) found no all-cause mortality benefit at low intake once you correct for the fact that many “non-drinkers” quit because they were already ill. The WHO’s position is that there’s no safe level. This isn’t moralising — it’s that the protective “J-curve” was mostly a statistical artefact.',
    how: [
      'Fewer drinks is better than more; zero is the lowest-risk point. That’s the whole shape of it.',
      'Set a couple of alcohol-free days a week as a floor, then see if it drifts down from there.',
      'Notice the sleep tax: alcohol fragments deep and REM sleep even when it helps you drop off.',
      'If cutting down feels hard rather than just annoying, that’s worth mentioning to your GP.',
    ],
    evidence: 'strong', effort: 2, cost: 'free',
    attribution: [{ who: 'Zhao et al.', what: 'Alcohol and all-cause mortality meta-analysis, JAMA Network Open (2023)' }, { who: 'World Health Organization', what: 'No safe level of alcohol (2023)' }],
    triggers: { answers: [{ q: 'alcohol_week', in: [] }], domain_below: 80 },
  },
  {
    id: 'caffeine-audit', domain: 'substances', tier: 'free', priority: 60,
    title: 'Move your caffeine earlier, not necessarily lower',
    tldr: 'For most people the issue isn’t how much caffeine but how late. An afternoon cut-off protects the sleep that everything else depends on.',
    why: 'Caffeine’s ~5–6 hour half-life means a mid-afternoon coffee is still working at bedtime. You often don’t have to quit — just move the last dose earlier. Because poor sleep drags down nearly every other domain, this is a small change with outsized reach.',
    how: [
      'Set a cut-off 8–10 hours before bed and hold it.',
      'Keep the morning coffee you enjoy; it’s the late one that’s costing you.',
      'Swap afternoon caffeine for decaf, herbal tea, or a short walk for the same ritual and energy.',
    ],
    evidence: 'moderate', effort: 1, cost: 'free',
    attribution: [{ who: 'Huberman Lab', what: 'Caffeine timing' }],
    triggers: { answers: [{ q: 'caffeine_late', in: ['daily', 'sometimes'] }] },
  },

  /* ================================================================ BODY */
  {
    id: 'know-your-numbers', domain: 'body', tier: 'free', priority: 85,
    title: 'Ask your doctor for a few basic numbers',
    tldr: 'A blood-pressure check and a basic blood panel are cheap or free, catch the quiet stuff early, and are things this site genuinely can’t do for you.',
    why: 'A habits score can’t see your blood pressure, cholesterol, or blood sugar — and those are exactly the things that cause serious trouble silently for years. This isn’t us diagnosing you; it’s us pointing you at the person who can. High blood pressure in particular is common, symptomless, and very treatable once known.',
    how: [
      'Get your blood pressure checked — many pharmacies do it free, and home monitors are cheap.',
      'At your next GP visit, ask whether a basic panel (lipids, blood sugar/HbA1c) makes sense for your age.',
      'Keep up the boring screenings you’re due for — they’re boring because they work.',
      'Write your numbers down so next year you can see the direction, not just the value.',
    ],
    evidence: 'strong', effort: 2, cost: 'low',
    attribution: [{ who: 'Peter Attia', what: 'Outlive — measure early, act early on the “four horsemen”' }],
  },
  {
    id: 'waist-to-height', domain: 'body', tier: 'free', priority: 55,
    title: 'Waist-to-height beats the bathroom scale',
    tldr: 'Keeping your waist under half your height is a better quick signal of metabolic risk than weight or BMI. It needs only a tape measure.',
    why: 'Where fat sits matters more than what you weigh; fat around the middle tracks with metabolic risk better than BMI. The simple rule of thumb — keep your waist under half your height — is a more useful home check than the scale, and it sidesteps the noise of muscle and frame.',
    how: [
      'Measure your waist at the belly button, relaxed, and compare it to half your height.',
      'Under half is the general target; over it is a nudge toward the movement and nutrition basics.',
      'Track the trend every month or two, not daily — day-to-day numbers are mostly water.',
      'This is one input, not a verdict. Treat it as information, not judgement.',
    ],
    evidence: 'moderate', effort: 1, cost: 'free',
    tags: ['weight_focus'],
    cautions: ['If measuring or tracking your body has ever tipped into something unhealthy for you, skip this one entirely — it isn’t worth it.'],
    attribution: [{ who: 'Ashwell & Gibson', what: 'Waist-to-height ratio as a screening tool, BMJ Open (2016)' }],
    triggers: { answers: [{ q: 'weight_self', in: ['bit_over', 'well_over'] }], exclude_flags: ['eating_disorder_history'] },
  },
  {
    id: 'oral-health', domain: 'body', tier: 'pro', priority: 40,
    title: 'Don’t skip the dentist',
    tldr: 'Gum health is linked to heart and metabolic health. Flossing and regular check-ups are a low-effort hedge.',
    why: 'Chronic gum inflammation is associated with cardiovascular and metabolic problems, plausibly through the same low-grade inflammation that drives them elsewhere. The causal picture isn’t fully settled, but the maintenance is cheap, easy, and worth doing regardless.',
    how: [
      'Brush twice a day and actually clean between your teeth once a day.',
      'See a dentist or hygienist on the schedule they recommend.',
      'Bleeding gums aren’t normal — mention them rather than ignoring them.',
    ],
    evidence: 'emerging', effort: 1, cost: 'low',
    attribution: [{ who: 'Sanz et al.', what: 'Periodontitis and cardiovascular disease consensus, J. Clinical Periodontology (2020)' }],
    triggers: {},
  },

  /* ============================================================== HABITS */
  {
    id: 'daily-outdoor-time', domain: 'habits', tier: 'free', priority: 80,
    title: 'Get an hour outdoors, in pieces',
    tldr: 'Outdoor time bundles daylight, movement, and often other people into one habit. The cheapest multi-domain win available.',
    why: 'Time outside quietly serves several domains at once: morning light for your body clock, incidental movement, frequently some social contact, and a genuine drop in stress markers. It’s less a single intervention than a container for several of the things that matter.',
    how: [
      'Aim for an hour outdoors across the day; it doesn’t have to be in one block.',
      'Front-load some of it into the morning so it doubles as circadian light.',
      'Attach it to things you already do — walk part of the commute, take calls outside, eat lunch out.',
      'Weather is rarely the real obstacle; the right coat usually solves it.',
    ],
    evidence: 'moderate', effort: 1, cost: 'free',
    attribution: [{ who: 'White et al.', what: 'Time in nature and health/wellbeing, Scientific Reports (2019)' }],
    triggers: { answers: [{ q: 'outside_time', in: ['bits', 'none'] }, { q: 'morning_light', in: ['sometimes', 'rarely'] }] },
  },
  {
    id: 'habit-stacking', domain: 'habits', tier: 'free', priority: 72,
    title: 'Attach new habits to old ones',
    tldr: 'The reliable way to build a habit isn’t motivation. It’s anchoring the new thing to something you already do without thinking.',
    why: 'Behaviour change fails mostly on triggers, not willpower: you forget, or the moment never announces itself. Anchoring a new habit to an existing routine (“after I start the kettle, I do ten squats”) borrows a trigger that already fires daily. Small and specific beats ambitious and vague.',
    how: [
      'Use the formula: “After I [existing habit], I will [tiny new habit].”',
      'Make the new habit almost embarrassingly small at first — two minutes, not twenty.',
      'Pick anchors that already happen without fail: kettle on, teeth brushed, front door.',
      'Let it grow on its own once it’s automatic; don’t force the size early.',
    ],
    evidence: 'moderate', effort: 1, cost: 'free',
    attribution: [{ who: 'BJ Fogg', what: 'Tiny Habits — anchoring behaviours' }, { who: 'James Clear', what: 'Atomic Habits — habit stacking' }],
    triggers: {},
  },
  {
    id: 'phone-friction', domain: 'habits', tier: 'pro', priority: 58,
    title: 'Design your phone to bother you less',
    tldr: 'You won’t out-discipline an app built to hold you; changing the environment beats fighting the pull.',
    why: 'Attention is engineered against you, and willpower is a poor defence over months. Small friction — greyscale, no notifications, the phone in another room — reliably beats trying harder, because it changes the default rather than the mood.',
    how: [
      'Turn off all non-essential notifications; keep calls and messages from real people, kill the rest.',
      'Move the attention-sink apps off the home screen, or log out so opening them takes effort.',
      'Set the phone to greyscale — it makes the whole thing markedly less compelling.',
      'Charge it outside the bedroom so the day doesn’t start and end with a screen.',
    ],
    evidence: 'emerging', effort: 1, cost: 'free',
    attribution: [{ who: 'Center for Humane Technology', what: 'Attention-design countermeasures' }],
    triggers: { answers: [{ q: 'phone_bed', in: ['in_bed', 'nearby'] }] },
  },
  {
    id: 'last-meal-timing', domain: 'habits', tier: 'pro', priority: 45,
    title: 'Nudge your last meal earlier',
    tldr: 'Eating closer to bedtime competes with sleep; shifting dinner earlier is a small lever on how rested you wake.',
    why: 'Late eating keeps digestion and core temperature elevated when both should be falling for sleep. Moving the last meal earlier is a gentle structural change — no fasting, no rules about quantity — that tends to improve how you sleep and wake.',
    how: [
      'Aim to finish eating 2–3 hours before bed on most nights.',
      'If dinner has to be late, keep it lighter and simpler.',
      'Treat it as a default to drift toward, not a rule to enforce when life intervenes.',
    ],
    evidence: 'emerging', effort: 1, cost: 'free',
    attribution: [{ who: 'Huberman Lab', what: 'Meal timing and sleep' }],
    triggers: { answers: [{ q: 'last_meal', in: ['late', 'varies'] }] },
  },
];

if (typeof module !== 'undefined') module.exports = { PROTOCOLS };
